(* ::Package:: *)

(* ::Input:: *)
(*ClearAll["Global`*"];*)
(**)
(*(* =========================================================*)*)
(*(*Frozen Stokes sphere model:2 real m=1 poloidal modes*)*)
(*(*Entirely in spherical coordinates*)*)
(*(* =========================================================*)*)
(**)
(*(*----------Safe numerical integration----------*)*)
(*SetAttributes[SafeNIntegrate,HoldAll];*)
(**)
(*SafeNIntegrate[expr_,vars__]:=Quiet[Chop[NIntegrate[Evaluate[expr],vars,Method->{"GlobalAdaptive","MaxErrorIncreases"->10000},AccuracyGoal->6,PrecisionGoal->6,MaxRecursion->8],10^-10],{NIntegrate::slwcon,NIntegrate::eincr,NIntegrate::inumr}];*)
(**)
(*(*----------Variables----------*)*)
(*(*r=radius,th=polar angle from z-axis,ph=azimuth*)*)
(*$Assumptions=r>1&&0<th<Pi&&0<=ph<=2 Pi;*)
(**)
(*(*----------Basic spherical vector operations----------*)*)
(*(*Components are always in the orthonormal spherical basis {e_r,e_th,e_ph}.*)*)
(**)
(*DotSph[A_,B_]:=Simplify[A[[1]] B[[1]]+A[[2]] B[[2]]+A[[3]] B[[3]]];*)
(**)
(*CurlSph[A_]:=Simplify[{(D[Sin[th] A[[3]],th]-D[A[[2]],ph])/(r Sin[th]),(D[A[[1]],ph]/Sin[th]-D[r A[[3]],r])/r,(D[r A[[2]],r]-D[A[[1]],th])/r}];*)
(**)
(*(*Directional derivative of a vector field A along a vector field V in the orthonormal spherical basis.*)*)
(*DirDerSph[V_,A_]:=Module[{Vr,Vt,Vp,Ar,At,Ap,T},Vr=V[[1]];Vt=V[[2]];Vp=V[[3]];*)
(*Ar=A[[1]];At=A[[2]];Ap=A[[3]];*)
(*T[f_]:=Vr D[f,r]+(Vt/r) D[f,th]+(Vp/(r Sin[th])) D[f,ph];*)
(*Simplify[{T[Ar]-(Vt At+Vp Ap)/r,T[At]+(Vt Ar-Vp Ap Cot[th])/r,T[Ap]+(Vp Ar+Vp At Cot[th])/r}]];*)
(**)
(*(*----------Explicit frozen Stokes base flow----------*)*)
(*urS[r_,th_]:=Cos[th] (1-3/(2 r)+1/(2 r^3));*)
(*uthS[r_,th_]:=-Sin[th] (1-3/(4 r)-1/(4 r^3));*)
(*uphS[r_,th_]:=0;*)
(**)
(*US={urS[r,th],uthS[r,th],uphS[r,th]};*)
(**)
(*Print["Frozen Stokes base flow U_S in spherical components:"];*)
(*Print[TraditionalForm[US]];*)
(**)
(*(*----------Real m=1 angular factors----------*)*)
(*Y1[th_,ph_]:=Sin[th] Cos[ph];                 (*l=1,real m=1*)*)
(*Y2[th_,ph_]:=Sin[th] Cos[th] Cos[ph];         (*l=2,real m=1*)*)
(**)
(*(*----------Radial profiles----------*)*)
(*psi1[r_]:=(r-1)^2/r^4;*)
(*psi2[r_]:=(r-1)^2/r^5;*)
(**)
(*(*----------Poloidal mode formula in spherical components----------*)*)
(*PoloidalMode[l_Integer,psiFun_,Y_]:=Module[{alpha},alpha=Simplify[D[r psiFun[r],r]/r];*)
(*Simplify[{l (l+1) psiFun[r] Y/r,alpha D[Y,th],alpha D[Y,ph]/Sin[th]}]];*)
(**)
(*Phi1=PoloidalMode[1,psi1,Y1[th,ph]];*)
(*Phi2=PoloidalMode[2,psi2,Y2[th,ph]];*)
(**)
(*Print["Phi1 (spherical components) = "];*)
(*Print[TraditionalForm[Phi1]];*)
(**)
(*Print["Phi2 (spherical components) = "];*)
(*Print[TraditionalForm[Phi2]];*)
(**)
(*(*----------Curls for the viscous bilinear form----------*)*)
(*CurlPhi1=CurlSph[Phi1]//FullSimplify;*)
(*CurlPhi2=CurlSph[Phi2]//FullSimplify;*)
(**)
(*basis={Phi1,Phi2};*)
(*curlBasis={CurlPhi1,CurlPhi2};*)
(**)
(*(*----------Volume element----------*)*)
(*vol=r^2 Sin[th];*)
(**)
(*(*----------Integrands with exact phi-integration----------*)*)
(*PhiIntegrated[expr_]:=FullSimplify[Integrate[expr,{ph,0,2 Pi}],Assumptions->r>1&&0<th<Pi];*)
(**)
(*(*----------Mass matrix----------*)*)
(*Mentry[i_,j_]:=Module[{integrand},integrand=PhiIntegrated[DotSph[basis[[j]],basis[[i]]] vol];*)
(*SafeNIntegrate[integrand,{r,1,Infinity},{th,0,Pi}]];*)
(**)
(*(*----------Viscous matrix---------- Using \[Integral]\[Del]u:\[Del]v=\[Integral]curl u\[CenterDot]curl v for divergence-free fields with homogeneous boundary conditions.*)*)
(*Dentry[i_,j_]:=Module[{integrand},integrand=PhiIntegrated[DotSph[curlBasis[[j]],curlBasis[[i]]] vol];*)
(*SafeNIntegrate[integrand,{r,1,Infinity},{th,0,Pi}]];*)
(**)
(*(*----------Convective/shear matrix----------*)*)
(*Kentry[i_,j_]:=Module[{integrand,convShear},convShear=-(DirDerSph[US,basis[[j]]]+DirDerSph[basis[[j]],US])//FullSimplify;*)
(*integrand=PhiIntegrated[DotSph[convShear,basis[[i]]] vol];*)
(*SafeNIntegrate[integrand,{r,1,Infinity},{th,0,Pi}]];*)
(**)
(*(*----------Assemble matrices----------*)*)
(*M=Table[Mentry[i,j],{i,1,2},{j,1,2}]//Chop;*)
(*Dmat=Table[Dentry[i,j],{i,1,2},{j,1,2}]//Chop;*)
(*Kmat=Table[Kentry[i,j],{i,1,2},{j,1,2}]//Chop;*)
(**)
(*Print["M = ",MatrixForm[M]];*)
(*Print["D = ",MatrixForm[Dmat]];*)
(*Print["K = ",MatrixForm[Kmat]];*)
(**)
(*(*----------Reduced matrix----------*)*)
(*Bvisc=LinearSolve[M,Dmat]//Chop;*)
(*Bconv=LinearSolve[M,Kmat]//Chop;*)
(*B[Re_]:=(Bconv-Bvisc/Re)//Chop;*)
(**)
(*Print["Bconv = ",MatrixForm[Bconv]];*)
(*Print["Bvisc = ",MatrixForm[Bvisc]];*)
(**)
(*(*----------Exact 2x2 eigenvalue formula----------*)*)
(*a=N[Bvisc[[1,1]]];*)
(*b=N[Bvisc[[2,2]]];*)
(*p=N[-Bconv[[1,2]]];*)
(*q=N[Bconv[[2,1]]];*)
(**)
(*Print["a = ",a];*)
(*Print["b = ",b];*)
(*Print["p = ",p];*)
(*Print["q = ",q];*)
(**)
(*Reosc=Abs[b-a]/(2 Sqrt[p q]);*)
(*Print["Reosc = ",N[Reosc,10]];*)
(**)
(*reEig[Re_]:=-(a+b)/(2 Re);*)
(*imEig[Re_]:=(1/2) Sqrt[Max[0,4 p q-((b-a)/Re)^2]];*)
(**)
(*(*----------Plot----------*)*)
(*Plot[{reEig[Re],imEig[Re],-imEig[Re]},{Re,0.1,400},PlotStyle->{{Blue,Thick},{Red,Dashed,Thick},{Red,Dashed,Thick}},AxesLabel->{"Re","eigenvalue components"},GridLines->{{Reosc},{0}},PlotRange->{{0,400},{-0.5,0.5}},ImageSize->Large]*)



