(* ::Package:: *)

(* ::Input:: *)
(*ClearAll["Global`*"];*)
(**)
(*(* =========================================================*)*)
(*(*Corrected Stokes sphere model:*)*)
(*(*-reduced first-order axisymmetric base correction*)*)
(*(*-3 real m=1 poloidal perturbation modes*)*)
(*(*Entirely in spherical coordinates*)*)
(*(* =========================================================*)*)
(**)
(*(*----------Safe numerical integration----------*)*)
(*SetAttributes[SafeNIntegrate,HoldAll];*)
(**)
(*SafeNIntegrate[expr_,vars__]:=Quiet[Chop[NIntegrate[Evaluate[expr],vars,Method->{"GlobalAdaptive","MaxErrorIncreases"->10000},AccuracyGoal->6,PrecisionGoal->6,MaxRecursion->8],10^-10],{NIntegrate::slwcon,NIntegrate::eincr,NIntegrate::inumr}];*)
(**)
(*(*----------Variables----------*)*)
(*(*r=radius,th=polar angle from z-axis,ph=azimuth*)*)
(*$Assumptions=r>1&&0<th<Pi&&0<=ph<=2 Pi;*)
(**)
(*(*----------Basic spherical vector operations----------*)*)
(*(*Components are always in the orthonormal spherical basis {e_r,e_th,e_ph}.*)*)
(**)
(*DotSph[A_,B_]:=Simplify[A[[1]] B[[1]]+A[[2]] B[[2]]+A[[3]] B[[3]]];*)
(**)
(*CurlSph[A_]:=Simplify[{(D[Sin[th] A[[3]],th]-D[A[[2]],ph])/(r Sin[th]),(D[A[[1]],ph]/Sin[th]-D[r A[[3]],r])/r,(D[r A[[2]],r]-D[A[[1]],th])/r}];*)
(**)
(*(*Directional derivative of a vector field A along V in the orthonormal spherical basis.*)*)
(*DirDerSph[V_,A_]:=Module[{Vr,Vt,Vp,Ar,At,Ap,T},Vr=V[[1]];Vt=V[[2]];Vp=V[[3]];*)
(*Ar=A[[1]];At=A[[2]];Ap=A[[3]];*)
(*T[f_]:=Vr D[f,r]+(Vt/r) D[f,th]+(Vp/(r Sin[th])) D[f,ph];*)
(*Simplify[{T[Ar]-(Vt At+Vp Ap)/r,T[At]+(Vt Ar-Vp Ap Cot[th])/r,T[Ap]+(Vp Ar+Vp At Cot[th])/r}]];*)
(**)
(*(*----------Explicit frozen Stokes base flow----------*)*)
(*urS[r_,th_]:=Cos[th] (1-3/(2 r)+1/(2 r^3));*)
(*uthS[r_,th_]:=-Sin[th] (1-3/(4 r)-1/(4 r^3));*)
(*uphS[r_,th_]:=0;*)
(**)
(*US={urS[r,th],uthS[r,th],uphS[r,th]};*)
(**)
(*Print["Frozen Stokes base flow U_S in spherical components:"];*)
(*Print[TraditionalForm[US]];*)
(**)
(*(*----------First nonlinear forcing F=(U_S\[CenterDot]\[Del]) U_S----------*)*)
(*Fforce=DirDerSph[US,US]//FullSimplify;*)
(**)
(*Print["Forcing F = (U_S \[CenterDot] \[Del]) U_S in spherical components:"];*)
(*Print[TraditionalForm[Fforce]];*)
(**)
(*(*----------General poloidal mode formula----------*)*)
(*(*For scalar S(r,th,ph)=psi(r) Y(th,ph),curl curl (S x) has spherical components:u_r=l(l+1) psi(r) Y/r u_th=(1/r) (d/dr (r psi)) dY/dth u_ph=(1/(r sin th)) (d/dr (r psi)) dY/dph*)*)
(*PoloidalMode[l_Integer,psiFun_,Y_]:=Module[{alpha},alpha=Simplify[D[r psiFun[r],r]/r];*)
(*Simplify[{l (l+1) psiFun[r] Y/r,alpha D[Y,th],alpha D[Y,ph]/Sin[th]}]];*)
(**)
(*(* =========================================================*)*)
(*(*PART A:reduced first-order base correction U1*)*)
(*(* =========================================================*)*)
(**)
(*(*----------Axisymmetric angular factors (m=0)----------*)*)
(*Yb1[th_]:=Cos[th];                          (*l=1,m=0*)*)
(*Yb2[th_]:=(3 Cos[th]^2-1)/2;             (*l=2,m=0*)*)
(**)
(*(*----------Radial profiles for base correction----------*)*)
(*psib1[r_]:=(r-1)^2/r^4;*)
(*psib2[r_]:=(r-1)^2/r^5;*)
(**)
(*B1=PoloidalMode[1,psib1,Yb1[th]]//FullSimplify;*)
(*B2=PoloidalMode[2,psib2,Yb2[th]]//FullSimplify;*)
(**)
(*CurlB1=CurlSph[B1]//FullSimplify;*)
(*CurlB2=CurlSph[B2]//FullSimplify;*)
(**)
(*baseBasis={B1,B2};*)
(*curlBaseBasis={CurlB1,CurlB2};*)
(**)
(*Print["Axisymmetric correction basis B1 = "];*)
(*Print[TraditionalForm[B1]];*)
(*Print["Axisymmetric correction basis B2 = "];*)
(*Print[TraditionalForm[B2]];*)
(**)
(*(*----------Volume element----------*)*)
(*vol=r^2 Sin[th];*)
(**)
(*(*----------phi-integration helper----------*)*)
(*PhiIntegrated[expr_]:=FullSimplify[Integrate[expr,{ph,0,2 Pi}],Assumptions->r>1&&0<th<Pi];*)
(**)
(*(*----------Reduced forced Stokes solve for U1----------*)*)
(*Sentry[i_,j_]:=Module[{integrand},integrand=PhiIntegrated[DotSph[curlBaseBasis[[j]],curlBaseBasis[[i]]] vol];*)
(*SafeNIntegrate[integrand,{r,1,Infinity},{th,0,Pi}]];*)
(**)
(*RHSentry[i_]:=Module[{integrand},integrand=PhiIntegrated[-DotSph[Fforce,baseBasis[[i]]] vol];*)
(*SafeNIntegrate[integrand,{r,1,Infinity},{th,0,Pi}]];*)
(**)
(*Smat=Table[Sentry[i,j],{i,1,2},{j,1,2}]//Chop;*)
(*RHS=Table[RHSentry[i],{i,1,2}]//Chop;*)
(**)
(*coeff=LinearSolve[Smat,RHS]//Chop;*)
(**)
(*Print["Reduced Stokes correction matrix S = ",MatrixForm[Smat]];*)
(*Print["Reduced Stokes forcing RHS = ",MatrixForm[RHS]];*)
(*Print["Correction coefficients {c1,c2} = ",coeff];*)
(**)
(*U1red=coeff[[1]] B1+coeff[[2]] B2//FullSimplify;*)
(**)
(*Print["Reduced first correction U1red = "];*)
(*Print[TraditionalForm[U1red]];*)
(**)
(*(* =========================================================*)*)
(*(*PART B:3-mode real m=1 perturbation chain*)*)
(*(* =========================================================*)*)
(**)
(*(*----------Real m=1 angular factors----------*)*)
(*Y1[th_,ph_]:=Sin[th] Cos[ph];                             (*l=1,m=1*)*)
(*Y2[th_,ph_]:=Sin[th] Cos[th] Cos[ph];                    (*l=2,m=1*)*)
(*Y3[th_,ph_]:=Sin[th] (5 Cos[th]^2-1) Cos[ph];         (*l=3,m=1*)*)
(**)
(*(*----------Radial profiles----------*)*)
(*psi1[r_]:=(r-1)^2/r^4;*)
(*psi2[r_]:=(r-1)^2/r^5;*)
(*psi3[r_]:=(r-1)^2/r^6;*)
(**)
(*Phi1=PoloidalMode[1,psi1,Y1[th,ph]]//FullSimplify;*)
(*Phi2=PoloidalMode[2,psi2,Y2[th,ph]]//FullSimplify;*)
(*Phi3=PoloidalMode[3,psi3,Y3[th,ph]]//FullSimplify;*)
(**)
(*CurlPhi1=CurlSph[Phi1]//FullSimplify;*)
(*CurlPhi2=CurlSph[Phi2]//FullSimplify;*)
(*CurlPhi3=CurlSph[Phi3]//FullSimplify;*)
(**)
(*basis={Phi1,Phi2,Phi3};*)
(*curlBasis={CurlPhi1,CurlPhi2,CurlPhi3};*)
(**)
(*Print["Phi1 = "];*)
(*Print[TraditionalForm[Phi1]];*)
(*Print["Phi2 = "];*)
(*Print[TraditionalForm[Phi2]];*)
(*Print["Phi3 = "];*)
(*Print[TraditionalForm[Phi3]];*)
(**)
(*(*----------Mass and viscous matrices----------*)*)
(*Mentry[i_,j_]:=Module[{integrand},integrand=PhiIntegrated[DotSph[basis[[j]],basis[[i]]] vol];*)
(*SafeNIntegrate[integrand,{r,1,Infinity},{th,0,Pi}]];*)
(**)
(*Dentry[i_,j_]:=Module[{integrand},integrand=PhiIntegrated[DotSph[curlBasis[[j]],curlBasis[[i]]] vol];*)
(*SafeNIntegrate[integrand,{r,1,Infinity},{th,0,Pi}]];*)
(**)
(*(*----------Convective/shear contribution from frozen base U_S----------*)*)
(*K0entry[i_,j_]:=Module[{convShear,integrand},convShear=-(DirDerSph[US,basis[[j]]]+DirDerSph[basis[[j]],US])//FullSimplify;*)
(*integrand=PhiIntegrated[DotSph[convShear,basis[[i]]] vol];*)
(*SafeNIntegrate[integrand,{r,1,Infinity},{th,0,Pi}]];*)
(**)
(*(*----------Convective/shear contribution from reduced correction U1red----------*)*)
(*K1entry[i_,j_]:=Module[{convShear,integrand},convShear=-(DirDerSph[U1red,basis[[j]]]+DirDerSph[basis[[j]],U1red])//FullSimplify;*)
(*integrand=PhiIntegrated[DotSph[convShear,basis[[i]]] vol];*)
(*SafeNIntegrate[integrand,{r,1,Infinity},{th,0,Pi}]];*)
(**)
(*M=Table[Mentry[i,j],{i,1,3},{j,1,3}]//Chop;*)
(*Dmat=Table[Dentry[i,j],{i,1,3},{j,1,3}]//Chop;*)
(*K0mat=Table[K0entry[i,j],{i,1,3},{j,1,3}]//Chop;*)
(*K1mat=Table[K1entry[i,j],{i,1,3},{j,1,3}]//Chop;*)
(**)
(*Print["M = ",MatrixForm[M]];*)
(*Print["D = ",MatrixForm[Dmat]];*)
(*Print["K0 = ",MatrixForm[K0mat]];*)
(*Print["K1 = ",MatrixForm[K1mat]];*)
(**)
(*(*----------Reduced corrected matrix----------*)*)
(*Bvisc=LinearSolve[M,Dmat]//Chop;*)
(*Bconv0=LinearSolve[M,K0mat]//Chop;*)
(*Bconv1=LinearSolve[M,K1mat]//Chop;*)
(**)
(*B[Re_]:=(Bconv0+Re Bconv1-Bvisc/Re)//Chop;*)
(**)
(*Print["Bconv0 = ",MatrixForm[Bconv0]];*)
(*Print["Bconv1 = ",MatrixForm[Bconv1]];*)
(*Print["Bvisc  = ",MatrixForm[Bvisc]];*)
(**)
(*(* =========================================================*)*)
(*(*Branch tracking and plotting*)*)
(*(* =========================================================*)*)
(**)
(*(*Distinguished upper-half-plane branch:if the spectrum is all real,use the average of the closest real pair;*)
(*otherwise use the eigenvalue with positive imaginary part.*)*)
(*TrackedBranch[RR_?NumericQ]:=Module[{ev,pos,revals,idx},ev=Eigenvalues[N[B[RR],40]];*)
(*pos=Select[ev,Im[#]>10^-10&];*)
(*If[pos=!={},First@SortBy[pos,-Im[#]&],revals=Sort[Re/@ev];*)
(*idx=Ordering[Abs[Differences[revals]],1][[1]];*)
(*(revals[[idx]]+revals[[idx+1]])/2]];*)
(**)
(*reGrid=N@Subdivide[0.1,500,1500];*)
(**)
(*branchData=Table[Module[{lam=TrackedBranch[RR]},{RR,Re[lam],Im[lam]}],{RR,reGrid}];*)
(**)
(**)
(*(*first oscillatory onset*)*)
(*oscCandidates=Select[branchData,Abs[#[[3]]]>10^-8&];*)
(*If[oscCandidates=!={},Reosc=oscCandidates[[1,1]];*)
(*Print["First complex branch appears near Re = ",N[Reosc,8]];];*)
(**)
(*(*closest approach to imaginary axis among the complex branch*)*)
(*complexData=Select[branchData,Abs[#[[3]]]>10^-8&];*)
(*If[complexData=!={},nearHopf=MaximalBy[complexData,#[[2]]&][[1]];*)
(*Print["Closest approach to axis near Re = ",nearHopf[[1]]];*)
(*Print["lambda(Re) \[TildeTilde] ",nearHopf[[2]]," + ",nearHopf[[3]]," i"];];*)
(**)
(*ListLinePlot[{({#[[1]],#[[2]]}&/@branchData),({#[[1]],#[[3]]}&/@branchData),({#[[1]],-#[[3]]}&/@branchData)},PlotStyle->{{Blue,Thick},{Red,Dashed,Thick},{Red,Dashed,Thick}},AxesLabel->{"Re","eigenvalue components"},GridLines->{If[ValueQ[Reosc],{Reosc},{}],{0}},PlotRange->{{0,500},{-0.5,0.5}},ImageSize->Large]*)



